package io.github.slupik.schemablock.model.ui.error;

/**
 * All rights reserved & copyright ©
 */
public enum AlgorithmErrorType {
    INCOMPATIBLE_TYPE,
    EXPECTED_ARRAY,
    NUMBER_TOO_BIG,
    TYPE_OF_ARRAY_AFTER_KEYWORD_NEW_NOT_FOUND,
    UNKNOWN_OPERATION,
    VARIABLE_IS_ALREADY_DEFINED,
    NEXT_ELEMENT_NOT_FOUND,
    VARIABLE_NOT_FOUND,
    ELEMENT_NOT_FOUND,
    ILLEGAL_CHAR_EXCEPTION,
    FUNCTION_NOT_EXISTS,
    NAME_OF_VARIABLE_NOT_FOUND_DURING_DECLARATION,
    ILLEGAL_OPERATION,
    INDEX_OUT_OF_BOUNDS
}
